services:
  # --- FRONTEND ---
  whiteboard-frontend:
    build:
      context: ../WhiteBoard_Frontend
    container_name: whiteboard_ui
    ports:
      - "80:80"
    restart: always
    depends_on:
      - whiteboard-backend

  # --- BACKEND ---
  whiteboard-backend:
    build: .
    container_name: whiteboard_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - MONGO_URI=mongodb://root:123456@mongo_db:27017/whiteboard_db?authSource=admin
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - DATABASE_URL=mysql://root:123456@mysql:3306/Test_NodeJS
    depends_on:
      mysql:
        condition: service_healthy
      mongo_db:
        condition: service_started
      redis_cache:
        condition: service_started

  # --- MYSQL ---
  mysql:
    image: mysql:8.0
    container_name: whiteboard-sql-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Test_NodeJS
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  # --- MONGO ---
  mongo_db:
    image: mongo:7
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- REDIS ---
  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  mongo_data:
  redis_data: